ADTsk Updated

diff --git a/0x1A-application_server/4-reload_gunicorn_no_downtime b/0x1A-application_server/4-reload_gunicorn_no_downtime
--- a/0x1A-application_server/4-reload_gunicorn_no_downtime
+++ b/0x1A-application_server/4-reload_gunicorn_no_downtime
@@ -7,8 +7,14 @@ if ! command -v pgrep > /dev/null; then
     exit 1
 fi
 
+# Ensure `pkill` is available
+if ! command -v pkill > /dev/null; then
+    echo "pkill command not found. Please install it to proceed."
+    exit 1
+fi
+
 # Get the PID of the Gunicorn master process
-PID=$(pgrep -x "gunicorn")
+PID=$(pgrep -f 'gunicorn: master' | head -n 1)
 
 if [ -n "$PID" ]; then
     # Send SIGHUP to the Gunicorn master process for a graceful restart
